@extends('admin.agency.layout')
@section('agency-heading', 'Đăng ký & hành khách')
@section('agency-description', 'Tìm và xử lý đăng ký, hành khách, giao dịch theo từng tour.')
@section('agency-body')
<section class="agency-panel" id="bookings"><div class="agency-panel__head"><h2><i class="fas fa-clipboard-list text-info mr-2"></i>Đăng ký & hành khách</h2><span class="agency-muted">{{ $bookings->total() }} đăng ký phù hợp</span></div><div class="agency-panel__body">
        <form method="get" action="{{ route('agency.bookings.index') }}" class="border rounded p-3 mb-4 bg-light">
            <div class="agency-fields">
                <label>Mã hoặc khách hàng<input class="form-control" name="q" value="{{ request('q') }}" placeholder="Mã, tên, email, điện thoại"></label>
                <label>Tour<select class="form-control" name="tour_id"><option value="">Tất cả tour</option>@foreach($tours as $tour)<option value="{{ $tour->id }}" @selected((string)request('tour_id')===(string)$tour->id)>{{ $tour->t_title }}</option>@endforeach</select></label>
                <label>Đợt khởi hành<select class="form-control" name="schedule_id"><option value="">Tất cả đợt</option>@foreach($tours as $tour)@foreach($tour->schedules as $schedule)<option value="{{ $schedule->id }}" @selected((string)request('schedule_id')===(string)$schedule->id)>{{ $tour->t_title }} · {{ substr($schedule->ts_start_date,0,10) }}</option>@endforeach @endforeach</select></label>
                <label>Trạng thái<select class="form-control" name="status"><option value="">Tất cả</option>@foreach(\App\Models\BookTour::STATUS as $key=>$label)<option value="{{ $key }}" @selected((string)request('status')===(string)$key)>{{ $label }}</option>@endforeach</select></label>
                <label>Từ ngày đăng ký<input class="form-control" type="date" name="from" value="{{ request('from') }}"></label>
                <label>Đến ngày đăng ký<input class="form-control" type="date" name="to" value="{{ request('to') }}"></label>
            </div>
            <button class="btn btn-primary mt-3"><i class="fas fa-search mr-1"></i> Tìm đăng ký</button>
            <a class="btn btn-link mt-3" href="{{ route('agency.bookings.index') }}">Xóa bộ lọc</a>
        </form>
        @forelse($bookings as $booking)
            <details><summary>{{ $booking->display_code }} · {{ $booking->b_name }} <small class="agency-muted">{{ $booking->tour->t_title }} · {{ $booking->total_guests }} khách · {{ number_format($booking->total_price) }} VND</small><span class="badge badge-info float-right">{{ \App\Models\BookTour::STATUS[$booking->b_status] }}</span></summary><div class="agency-inner"><p>{{ $booking->b_email }} · {{ $booking->b_phone }} · {{ $booking->b_start_date?->format('d/m/Y') }} – {{ $booking->b_end_date?->format('d/m/Y') }}</p><p><strong>Chính sách khi đặt:</strong> {{ $booking->policy_snapshot ?: 'Đăng ký cũ chưa lưu chính sách.' }}<br><strong>Lý do hủy:</strong> {{ $booking->b_cancel_reason ?: '—' }}</p>
                @if(count(\App\Models\BookTour::ALLOWED_TRANSITIONS[$booking->b_status]??[]))<form class="border rounded p-3 mb-3" method="post" action="{{ route('agency.booking.status',$booking->id) }}">@csrf<div class="agency-fields"><label>Chuyển trạng thái<select class="form-control" name="status">@foreach(\App\Models\BookTour::ALLOWED_TRANSITIONS[$booking->b_status]??[] as $status)<option value="{{ $status }}">{{ \App\Models\BookTour::STATUS[$status] }}</option>@endforeach</select></label><label>Lý do từ chối / hủy, ghi chú<textarea class="form-control" name="note"></textarea></label></div><button class="btn btn-primary btn-sm mt-3">Cập nhật trạng thái</button></form>@endif
                <h3 class="h6 font-weight-bold mt-4">Hành khách</h3>@foreach($passengers[$booking->id]??[] as $passenger)@include('agency.passenger-form')@endforeach @if(count($passengers[$booking->id]??[])<$booking->total_guests)@include('agency.passenger-form',['passenger'=>new \App\Models\BookingPassenger])@endif
                <h3 class="h6 font-weight-bold mt-4">Giao dịch thu / hoàn</h3><div class="agency-scroll"><table class="agency-table"><thead><tr><th>Thời điểm</th><th>Loại</th><th>Chứng từ</th><th>Số tiền</th><th>Ghi chú</th></tr></thead><tbody>@foreach($ledger[$booking->id]??[] as $entry)<tr><td>{{ $entry->occurred_at->format('d/m/Y H:i') }}</td><td>{{ $entry->type==='receipt'?'Thu':'Hoàn' }}</td><td>{{ $entry->reference }}</td><td>{{ number_format($entry->amount) }}</td><td>{{ $entry->note }}</td></tr>@endforeach @foreach($payments[$booking->id]??[] as $entry)<tr><td>{{ $entry->updated_at->format('d/m/Y H:i') }}</td><td>VNPay</td><td>{{ $entry->reference }}</td><td>{{ number_format($entry->amount) }}</td><td>{{ $entry->status==='review'?'Chờ đối soát':'Đã thanh toán' }}</td></tr>@endforeach</tbody></table></div>
                <details><summary>Ghi sổ thu / hoàn tiền</summary><div class="agency-inner"><p class="agency-muted">Chỉ ghi nhận giao dịch đã thực hiện. Hoàn tiền cần hủy đăng ký và đối chiếu chính sách đã lưu.</p><form method="post" action="{{ route('agency.transaction',$booking->id) }}">@csrf<div class="agency-fields"><label>Loại<select class="form-control" name="type"><option value="receipt">Thu tiền</option><option value="refund">Hoàn tiền</option></select></label><label>Số tiền VND<input class="form-control" name="amount" type="number" min="1" required></label><label>Mã chứng từ<input class="form-control" name="reference" required></label><label>Thời điểm<input class="form-control" name="occurred_at" type="datetime-local" required></label></div><label class="mt-3">Ghi chú / căn cứ chính sách<textarea class="form-control" name="note" required></textarea></label><button class="btn btn-primary mt-3">Ghi sổ</button></form></div></details>
            </div></details>
        @empty<p class="text-muted">Không có đăng ký phù hợp bộ lọc.</p>@endforelse
        <div class="mt-3">{{ $bookings->links() }}</div>
    </div></section>
@endsection
