@extends('admin.agency.layout')
@section('agency-heading', 'Hồ sơ đại lý')
@section('agency-description', 'Cập nhật tài khoản nhân sự và thông tin đại lý hiển thị với khách hàng.')
@section('agency-body')
<section class="agency-panel" id="profile"><div class="agency-panel__head"><h2><i class="fas fa-id-card text-info mr-2"></i>Tài khoản & hồ sơ đại lý</h2><a href="{{ route('admin.change.password') }}">Đổi mật khẩu</a></div><div class="agency-panel__body">
        <div class="d-flex align-items-center mb-4" style="gap:15px">@if($agency->logo)<img class="agency-logo" src="{{ asset(pare_url_file($agency->logo)) }}" alt="Logo {{ $agency->name }}">@else<div class="agency-logo d-flex align-items-center justify-content-center"><i class="fas fa-building fa-2x text-muted"></i></div>@endif<div><strong>{{ auth('admins')->user()->name }}</strong><div class="agency-muted">{{ auth('admins')->user()->email }}</div><div class="agency-muted">Xác minh: {{ $agency->verification_status }} · Phí nền tảng: {{ $agency->commission_basis_points/100 }}%</div></div></div>
        <h3 class="h6 font-weight-bold">Thông tin đăng nhập của tôi</h3>
        <form method="post" action="{{ route('agency.account') }}" class="mb-4">@csrf<div class="agency-fields"><label>Họ tên nhân sự *<input class="form-control" name="account_name" value="{{ old('account_name',auth('admins')->user()->name) }}" required></label><label>Email đăng nhập *<input class="form-control" type="email" name="account_email" value="{{ old('account_email',auth('admins')->user()->email) }}" required></label><label>Điện thoại cá nhân<input class="form-control" name="account_phone" value="{{ old('account_phone',auth('admins')->user()->phone) }}"></label></div><button class="btn btn-outline-primary mt-3"><i class="fas fa-user-check mr-1"></i> Lưu tài khoản</button></form>
        <h3 class="h6 font-weight-bold border-top pt-4">Hồ sơ đại lý hiển thị với khách hàng</h3>
        <form method="post" action="{{ route('agency.profile') }}" enctype="multipart/form-data">@csrf<div class="agency-fields"><label>Tên đại lý *<input class="form-control" name="name" value="{{ old('name',$agency->name) }}" required></label><label>Địa chỉ<input class="form-control" name="address" value="{{ old('address',$agency->address) }}"></label><label>Điện thoại<input class="form-control" name="phone" value="{{ old('phone',$agency->phone) }}"></label><label>Email liên hệ<input class="form-control" type="email" name="email" value="{{ old('email',$agency->email) }}"></label></div><div class="row mt-3"><div class="col-md-6"><label>Mô tả đại lý<textarea class="form-control" name="description" rows="4">{{ old('description',$agency->description) }}</textarea></label></div><div class="col-md-6"><label>Thông tin xác minh<textarea class="form-control" name="verification_information" rows="4">{{ old('verification_information',$agency->verification_information) }}</textarea></label></div></div><label class="mt-3">Logo (JPG, PNG, WebP)<input class="form-control-file mt-2" type="file" name="logo" accept="image/jpeg,image/png,image/webp"></label><button class="btn btn-primary mt-3"><i class="fas fa-save mr-1"></i> Lưu hồ sơ</button></form>
    </div></section>
@endsection
